### ISSUE TITLE
Problems with Notebook and Data file

### ISSUE THREAD

**Issue by joesoap99** [phgupta/Blog#1]
Hi,

The notebook does not load into Jupyter (Python 3.6) as there is a JSON error indicated.

The data file seems to be in a JSON format. It is not in CSV format.

**Comment by phgupta** [comment]
Could you elaborate on the error and add a screenshot? I ran the notebook again and it seems to work perfectly well for me.

**Comment by joesoap99** [comment]
Pranav,

 

Thank you

I re-downloaded and ran the files successfully.

There must have been some corruption with my original download.

 

Sorry to bother you.

 

Robert
